backend:
  name: github
  repo: ThomasNettleship/decap-test
  base_url: https://decap.nettleship.net

#publish_mode: editorial_workflow
media_folder: /images/uploads
public_folder: /images/uploads

collections:
  - name: 'posts'
    label: 'Posts'
    label_singular: 'Post'
    folder: '_posts'
    slug: '{{year}}-{{month}}-{{day}}-{{title}}'
    create: true
    editor:
      visualEditing: true
    view_filters:
      - label: Posts With Index
        field: title
        pattern: 'This is post #'
      - label: Posts Without Index
        field: title
        pattern: front matter post
      - label: Drafts
        field: draft
        pattern: true
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
      - label: Drafts
        field: draft
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Author', name: 'author', widget: 'string', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown', hint: 'Main content goes here.' }
